name: Create Release

on:
  pull_request:
    branches:
      - production
    types:
      - closed
  workflow_dispatch:
    inputs:
      increment_type:
        type: choice
        description: Version increment type
        default: patch
        options:
          - patch
          - minor
          - major
      version:
        type: string
        description: Specific release version (e.g., 1.2.3)

jobs:
  create_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Extract release version from Pull Request title
        id: extract-version-from-pr-title
        shell: bash
        if: ${{ !github.event.inputs.version && github.event.pull_request.merged }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          VERSION_REGEX="(\d+\.\d+\.\d+)"

          MATCH_RESULT=$( [[ $PR_TITLE =~ $VERSION_REGEX ]]; echo $? )

          # Echo the result
          echo "Match Result: $MATCH_RESULT"
          echo "Match Result 2: $BASH_REMATCH[0]"
          echo "Match Result 2: $MATCH_RESULT[0]"

          if [[ MATCH_RESULT != 0 ]]; then
            VERSION="${BASH_REMATCH[0]}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "No version (x.y.z) found in the PR title."
          fi

      - name: Determine incremented release version
        id: determine-incremented-release-version
        if: ${{ !github.event.inputs.version && !steps.extract-version-from-pr-title.outputs.version }}
        uses: reecetech/version-increment@2023.9.3
        with:
          scheme: semver
          increment: ${{ github.event.inputs.increment_type }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version ||
            steps.extract-version-from-pr-title.outputs.version ||
            steps.determine-incremented-release-version.outputs.version }}
          generate_release_notes: true

      - name: Get color
        run: echo "The selected color is ${{ steps.extract-version-from-pr-title.outputs.version }}"
